name: first-workflow
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "step 1"
      - name: step2
        run: echo "step 2"
  jobs2:
    runs-on: ubuntu-latest
    steps:      
      - name: cows
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: 'a cow'
          color: 'red'
    
